adminapp/urls.py
from django.urls import path

from adminapp.views import (
    AddAnimal,
    AddUser,
    AnimalDeleteView,
    CreateType,
    DeleteType,
    DetailAnimal,
    EditAnimal,
    EditType,
    ShowAnimal,
    ShowUsers,
    UserDeleteView,
)

app_name = "adminapp"

urlpatterns = [
    path("add_type/create/", CreateType.as_view(), name="add_type"),
    path("delete_type/<int:pk>/", DeleteType.as_view(), name="delete_type"),
    path("edit_type/<int:pk>/", EditType.as_view(), name="edit_type"),
    path("add_animal/<int:pk>/", AddAnimal.as_view(), name="add_animal"),
    path("edit_animal/<int:pk>/", EditAnimal.as_view(), name="edit_animal"),
    path("delete_animal/<int:pk>/", AnimalDeleteView.as_view(), name="delete_animal"),
    path("show_animals/<int:pk>/", ShowAnimal.as_view(), name="show_animal"),
    path("detail_animals/<int:pk>/", DetailAnimal.as_view(), name="detail_animal"),
    path("add_user/", AddUser.as_view(), name="add_user"),
    path("delete_user/<int:pk>/", UserDeleteView.as_view(), name="delete_user"),
    path("show_users/", ShowUsers.as_view(), name="show_users"),
]

authapp/urls.py
from django.urls import path

from .views import change, login, logout, register, verify

app_name = "authapp"
urlpatterns = [
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("register", register, name="register"),
    path("change/", change, name="change"),
    path("verify/<email>/<activation_key>/", verify, name="verify"),
]

house_with_a_tial/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mainapp.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("", include("social_django.urls", namespace="social")),
    path("types/", include("mainapp.urls", namespace="mainapp")),
    path("auth/", include("authapp.urls", namespace="authapp")),
    path("basket/", include("basketapp.urls", namespace="basketapp")),
    path("adminapp/", include("adminapp.urls", namespace="adminapp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django.forms import ModelForm

from mainapp.models import Animal, TypeOfAnimal


class EditAnimal(ModelForm):
    class Meta:
        model = Animal
        fields = "__all__"


class CreateAnimal(ModelForm):
    class Meta:
        model = Animal
        fields = ("type", "name", "age", "avatar", "short_description", "description")


class CreateType(ModelForm):
    class Meta:
        model = TypeOfAnimal
        fields = "__all__"

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from authapp.forms import UserRegisterForm
from authapp.models import User
from mainapp.models import Animal, TypeOfAnimal

from .forms import CreateAnimal, CreateType, EditAnimal


class CreateType(LoginRequiredMixin, CreateView):
    model = TypeOfAnimal
    template_name = "adminapp/create_type.html"
    fields = "__all__"

    def test_func(self):
        if self.request.user.is_superuser:
            return self.request.user

    def get_success_url(self):
        return reverse("adminapp:show_animal", args=[self.object.pk])


class DetailAnimal(LoginRequiredMixin, DetailView):
    model = Animal
    template_name = "adminapp/detail_animal.html"


class DeleteType(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = TypeOfAnimal
    template_name = "adminapp/delete_type.html"
    success_url = reverse_lazy("adminapp:show_animal", args=[0])

    def test_func(self):
        if self.request.user.is_superuser:
            return self.request.user


class EditType(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = TypeOfAnimal
    template_name = "adminapp/edit_type.html"
    fields = "__all__"

    def test_func(self):
        return self.request.user.is_superuser

    def get_success_url(self):
        return reverse("adminapp:show_animals", args=[self.kwargs["pk"]])


class AddAnimal(UserPassesTestMixin, LoginRequiredMixin, CreateView):
    model = Animal
    template_name = "adminapp/create_animal.html"
    fields = ("name", "age", "short_description", "description", "type")

    def get_initial(self):
        return {"type": self.kwargs["pk"]}

    def test_func(self):
        if self.request.user.is_superuser:
            return self.request.user

    def get_success_url(self):
        return reverse("adminapp:show_animal", args=[self.kwargs["pk"]])


class EditAnimal(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Animal
    template_name = "adminapp/edit_animal.html"
    fields = "__all__"

    def test_func(self):
        return self.request.user.is_superuser

    def get_success_url(self):
        animal_type = Animal.objects.get(pk=self.kwargs["pk"])
        return reverse("adminapp:show_animal", args=[animal_type.type_id])


class AnimalDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Animal
    template_name = "adminapp/delete_animal.html"

    def test_func(self):
        return self.request.user.is_superuser

    def get_success_url(self):
        animal = Animal.objects.get(pk=self.kwargs["pk"])
        return reverse("adminapp:show_animal", args=[animal.type_id])


class ShowAnimal(UserPassesTestMixin, LoginRequiredMixin, ListView):
    model = Animal
    template_name = "adminapp/main_admin.html"

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super(ShowAnimal, self).get_context_data(**kwargs)
        data["animal_types"] = TypeOfAnimal.objects.all()
        if self.kwargs["pk"] != 0:
            object_list = Animal.objects.filter(type=self.kwargs["pk"])
            data["object_list"] = object_list
            data["type_of_animal"] = get_object_or_404(TypeOfAnimal, pk=self.kwargs["pk"])
        return data


class AddUser(UserPassesTestMixin, LoginRequiredMixin, CreateView):
    model = User
    template_name = "adminapp/add_user.html"
    fields = ("username", "password", "email", "avatar")
    success_url = reverse_lazy("adminapp:show_users")

    def test_func(self):
        return self.request.user.is_superuser


class UserDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = User
    template_name = "adminapp/delete_user.html"
    success_url = reverse_lazy("adminapp:show_users")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def test_func(self):
        return self.request.user.is_superuser


class ShowUsers(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = User
    template_name = "adminapp/show_users.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super(ShowUsers, self).get_context_data(**kwargs)
        data["object_list"] = User.objects.all().order_by("-is_active", "username")
        return data

    def test_func(self):
        return self.request.user.is_superuser

adminapp/templates/adminapp/add_user.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form method="post" action="{% url 'adminapp:add_user' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Создать">
</form>
{% endblock content %}

adminapp/templates/adminapp/base.html
{% load static %}

{% block headers %}

{% endblock headers %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
{% endblock %}
<title>{{ title }}</title>
{% block javascript %}
{% endblock javascript %}
<div class="container">
    {% block menu %}
        {% include 'adminapp/includes/inc_admin_menu.html' %}
    {% endblock menu %}
    <br>
    {% block content %}
    {% endblock content %}
    <br>
    <a href="{% url 'adminapp:add_type'%}">Добавить категорию</a>
    <br>
    <a href="{% url 'adminapp:add_user' %}">Добваить пользователя</a>
    {% block footer %}
    {% endblock footer %}
</div>

adminapp/templates/adminapp/create_animal.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Сохранить">
</form>


{% endblock %}

adminapp/templates/adminapp/create_type.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Создать категорию">
</form>
{% endblock content %}

adminapp/templates/adminapp/delete_animal.html
{% extends 'adminapp/base.html' %}

{% block content %}
<div class="product_delete">
    Уверены, что хотите удалить животное <strong>{{ object.name }}</strong>?
    <form action="{% url 'adminapp:delete_animal' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <a href="{% url 'adminapp:detail_animal' object.pk %}" class="btn btn-success btn-block" role="button">
        отмена
    </a>
</div>
{% endblock content %}

adminapp/templates/adminapp/delete_type.html
{% extends 'adminapp/base.html' %}

{% block content %}
<div class="product_delete">
    Уверены, что хотите удалить категорию <strong>{{ object.name }}</strong>?
    <form action="{% url 'adminapp:delete_type' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <a href="{% url 'adminapp:show_animal' object.pk %}" class="btn btn-success btn-block" role="button">
        отмена
    </a>
</div>
{% endblock content %}

adminapp/templates/adminapp/delete_user.html
{% extends 'adminapp/base.html' %}

{% block content %}
<div class="product_delete">
    Уверены, что хотите удалить пользователя <strong>{{ object.name }}</strong>?
    <form action="{% url 'adminapp:delete_user' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <a href="{% url 'adminapp:show_users'%}" class="btn btn-success btn-block" role="button">
        отмена
    </a>
</div>
{% endblock content %}

adminapp/templates/adminapp/detail_animal.html
{% extends 'adminapp/base.html' %}

{% block menu %}
    {% for link in animal_types %}
        <a href="{% url 'adminapp:show_animal' link.pk %}">{{link.title}}</a>
    {% endfor %}
{% endblock menu %}
{% block content %}
{% if object.is_active %}
    {{object.name}}
    {{object.type}}
    {{object.age}}
{% endif %}
<br>
    <button class="home-animal">
        <a href="{% url 'adminapp:edit_animal' animal.pk %}">Изменить</a>
    </button>
<br>
    <button class="home-animal">
        <a href="{% url 'adminapp:delete_animal' animal.pk %}">Удалить</a>
    </button>
<br>
    <a href="{% url 'index' %}">На главную</a>
{% endblock content %}

adminapp/templates/adminapp/edit_animal.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Изменить">
    {% endblock content %}

adminapp/templates/adminapp/edit_type.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Изменить">
</form>

{% endblock content %}

adminapp/templates/adminapp/main_admin.html
{% extends 'adminapp/base.html' %}

{% block content %}
    {% for animal in object_list %}
        {% if animal.is_active %}
            <a href="{% url 'adminapp:detail_animal' animal.pk %}">{{animal.name}}</a>
            {{animal.type}}
            {{animal.age}}
            <br>
        {% endif %}
    {% endfor %}
{% if type_of_animal %}
    <br>
        <a href="{% url 'adminapp:delete_type' type_of_animal.pk %}">Удалить категорию</a>
    <br>
        <br>
            <a href="{% url 'adminapp:add_animal' type_of_animal.pk %}">Добавить животное</a>
        <br>
    <br>
        <a href="{% url 'adminapp:edit_type' type_of_animal.pk %}">Изменить категорию</a>
    <br>
{% endif %}
<br>
    <a href="{% url 'index' %}">На главную</a>
<br>
{% endblock content %}

adminapp/templates/adminapp/show_all_animals.html
{% extends 'adminapp/base.html' %}
{% block menu %}
    {% include 'adminapp/includes/inc_admin_menu.html' %}
{% endblock menu %}
{% block content %}
    {% for animal in object_list %}
    <a href="{% url 'adminapp:detail_animal' animal.pk %}">{{animal.name}}</a>
        {{animal.age}}
        {{animal.short_description}}
<br>
    {% endfor %}
{% endblock %}

adminapp/templates/adminapp/show_users.html
{% extends 'adminapp/base.html' %}

{% block content %}
    {% for user in object_list %}
        {%if user.is_active %}
            {{user.username}}
            {{user.first_name}}
            {{user.age}}
            {{user.address}}
            <a href="{% url 'adminapp:delete_user' user.pk %}">Удалить пользователя</a>
        {% endif %}
    <br>
    {% endfor %}
<a href="{% url 'adminapp:add_user' %}">Добавить пользователя</a>
{% endblock content %}