authapp/urls.py
from django.urls import path

from .views import change, login, logout, register, verify

app_name = "authapp"
urlpatterns = [
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("register", register, name="register"),
    path("change/", change, name="change"),
    path("verify/<email>/<activation_key>/", verify, name="verify"),
]

basketapp/urls.py
from django.urls import path

from .views import basket_add, basket_delete, basket_show, edit_basket

app_name = "basketapp"

urlpatterns = [
    path("", basket_show, name="basket_show"),
    path("add/<int:pk>/", basket_add, name="basket_add"),
    path("delete/<int:pk>/", basket_delete, name="basket_delete"),
    path("edit/<int:pk>/<int:quantity>/", edit_basket, name="edit_basket"),
]

house_with_a_tial/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mainapp.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("", include("social_django.urls", namespace="social")),
    path("types/", include("mainapp.urls", namespace="mainapp")),
    path("auth/", include("authapp.urls", namespace="authapp")),
    path("basket/", include("basketapp.urls", namespace="basketapp")),
    path("adminapp/", include("adminapp.urls", namespace="adminapp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from .views import animal_of_types, contact, person_animal

app_name = "mainapp"
urlpatterns = [
    path("", animal_of_types, name="typeanimal"),
    path("contact/", contact, name="contact"),
    path("<int:pk>/<int:page>/", animal_of_types, name="animaloftype"),
    path("animal/<int:pk>", person_animal, name="person_animal"),
]

mainapp/models.py
from datetime import datetime

from django.db import models


class TypeOfAnimal(models.Model):
    title = models.CharField(max_length=30, verbose_name="Вид животного")
    is_active = models.BooleanField(verbose_name="Доступен", default=True)

    def __str__(self):
        return f"{self.title}"

    def delete(self, using=None, keep_parents=False):
        if self.is_active:
            self.is_active = False
        else:
            self.is_active = True
        self.save()


class Animal(models.Model):
    type = models.ForeignKey(TypeOfAnimal, on_delete=models.CASCADE, verbose_name="Вид животного")
    name = models.CharField(max_length=30, verbose_name="Имя")
    age = models.PositiveSmallIntegerField(verbose_name="Примерный возраст", blank=True)
    avatar = models.ImageField(upload_to="animal_account", verbose_name="Аватарка")
    short_description = models.CharField(max_length=70, verbose_name="Краткое описание")
    description = models.TextField(verbose_name="Описание", blank=True)
    date_entrance = models.DateTimeField(auto_created=True, verbose_name="Дата поступления", default=datetime.now())
    is_active = models.BooleanField(verbose_name="Доступен", default=True)
    taken_home = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name="Забрали домой",
    )

    def __str__(self):
        return f"{self.type} {self.name}"

    def delete(self, using=None, keep_parents=False):
        if self.is_active:
            self.is_active = False
        else:
            self.is_active = True
        self.save()


class Contact(models.Model):
    address = models.CharField(max_length=1000, verbose_name="Адрес")
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    email = models.EmailField(verbose_name="Почта")

    def __str__(self):
        return "Контакты"

mainapp/views.py
from random import sample

from django.conf import settings
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render

from basketapp.models import Basket

from .models import Animal, Contact, TypeOfAnimal


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def rand_animal():
    hot_animal = Animal.objects.all()
    return sample(list(hot_animal), 1)[0]


def get_same_animal(rand_animal_):
    animals_category_rand_animal = Animal.objects.filter(type=rand_animal_.type).exclude(pk=rand_animal_.pk)[:2]
    return animals_category_rand_animal


def index(request):
    types = TypeOfAnimal.objects.all()
    all_animals = Animal.objects.all()
    rand_animal_ = rand_animal()
    get_same_animal_ = get_same_animal(rand_animal_)

    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    context = {
        "title": "Главная",
        "all_animals": all_animals,
        "basket": basket,
        "types": types,
        "media_url": settings.MEDIA_URL,
        "get_same_animal_": get_same_animal_,
        "rand_animal": rand_animal_,
    }
    return render(request, "mainapp/index.html", context)


def contact(request):
    contacts = Contact.objects.all()
    context = {"title": "Контакты", "contacts": contacts}
    return render(request, "mainapp/contact.html", context)


def animal_of_types(request, pk=None, page=1):
    types = TypeOfAnimal.objects.all()
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    if pk:
        animal_of_type = Animal.objects.filter(type=pk).order_by("name")
        type = TypeOfAnimal.objects.get(pk=pk)
    else:
        animal_of_type = Animal.objects.all().order_by("name")
        type = {"pk": 0, "name": "Все"}
    paginator = Paginator(animal_of_type, 2)
    try:
        animal_paginator = paginator.page(page)
    except PageNotAnInteger:
        animal_paginator = paginator.page(1)
    except EmptyPage:
        animal_paginator = paginator.page(paginator.num_pages)
    context = {
        "type": type,
        "animal_of_type": animal_paginator,
        "basket": basket,
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "mainapp/animal.html", context)


def person_animal(request, pk):
    animal = get_object_or_404(Animal, pk=pk)
    title = animal.name
    basket = get_basket(request.user)
    context = {"animal": animal, "title": title, "basket": basket}
    return render(request, "mainapp/person_animal.html", context)

mainapp/templates/mainapp/animal.html
{% extends 'mainapp/base.html' %}


{% block content %}
<div class="dop-menu">
    {% include 'mainapp/includes/inc_animal_type.html' %}
</div>
{% for animal in animal_of_type %}
<div class="card">
    {{animal.name}}
    <img class="avatar" src="{{media_url}}{{animal.avatar}}">
    {{animal.age}}
    <br>
    {{animal.short_description}}
    <button class="home-animal">
        <a href="{% url 'mainapp:person_animal' animal.pk %}">Посмотреть подробнее
        </a>
    </button>
</div>
{% endfor %}
{% if animal_of_type.has_previous %}
    <a href="{% url 'mainapp:animaloftype' type.pk animal_of_type.previous_page_number %}">Предыдущая</a>
{% endif %}
    <span> страница {{animaloftype.number}} из {{animaloftype.paginator.num_pages}} </span>
{% if animal_of_type.has_next %}
    <a href="{% url 'mainapp:animaloftype' type.pk animal_of_type.next_page_number  %}">Следущая</a>
{% endif %}
{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
{% block javascript %}
    <script src="{% static 'js/jquery-3.6.3.js' %}"></script>
    <script src="{% static 'js/basket.js' %}"></script>
{% endblock javascript %}

{% block header %}
<title>{{ title }}</title>
{% endblock header %}
<div class="container">
    {% block menu %}
        {% include 'mainapp/includes/inc_menu.html' %}
    {% endblock menu %}

    {% block content %}
    {% endblock content %}

    {% block footer %}
    {% endblock footer %}
</div>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}

{% block content %}
{% for contact in contacts %}
    <p>{{contact.phone}}</p>
    <p>{{contact.address}}</p>
{% endfor %}
{% endblock content %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block content %}
<div class="same-animal">
    Горячее предложение
    {{rand_animal.type}}
    {{rand_animal.name}}
</div>
{% for animal in get_same_animal_ %}
{% if animal.is_active %}
<div class="card">
    {{animal.name}}
    <img class="avatar" src="{{media_url}}{{animal.avatar}}">
    {{animal.age}} лет
    <br>
    {{animal.short_description}}
    <button class="home-animal">
        <a href="{% url 'basketapp:basket_add' animal.pk %}">Забрать домой</a>
    </button>
</div>
{% endif %}
{%endfor%}
{% endblock %}

mainapp/templates/mainapp/person_animal.html
{% extends 'mainapp/base.html' %}

{% block content %}
    {{animal.name}}
    {{animal.age}}
    {{animal.type}}
    <a href="{% url 'basketapp:basket_add' animal.pk %}" >забрать домой</a>
{% endblock content %}